workflows:
  android-workflow:
    name: Android Build
    working_directory: Mals-bot
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd Mals-bot
          flutter packages pub get
      - name: Build Android APK
        script: |
          cd Mals-bot
          flutter build apk --debug
    artifacts:
      - Mals-bot/build/**/outputs/**/*.apk
